### PR TITLE
Fix compiling error with latest PSA API

### PR DESCRIPTION
**Pull request by CharleyChu**
Signed-off-by: Charley Chu <haoc@cypress.com>

### CODE REVIEW

**Comment by davwan01** [comment]
Hi @Sherryzhang2, could you help to review?
Thanks.

**Review by Sherryzhang2 — APPROVED** [review]

**Comment by davwan01** [comment]
Hi @pfalcon ,
Can you please help to review this patch? (Sherry has reviewed)
Thanks.

**Comment by pfalcon** [comment]
> Can you please help to review this patch? (Sherry has reviewed)

So far, I'm playing catch up game, as I'm not too familiar with FreeRTOS or TF-M. One thing Linaro would like to help with is to add CI to test PRs (I have some progress with that, but the overall complication, as you may imagine, is that this repo is not a standalone, but a part of another big project).

One things I noticed is that the PRs coming to this repo are light on details. For example, I really appreciate your, @davwan01, and @Sherryzhang2's comments on https://github.com/Linaro/freertos-pkcs11-psa/pull/3, providing background of what the change is related to.

For this PR, there would be following questions:

1. "Fix compiling error with latest PSA API" - Are there any specific information about that? Are PSA API sets versioned, if so, which version this change corresponds to? Likewise, does it correspond to a particular release version of TF-M?
2. It would be helpful to have a brief description of the nature of the changes. For example, is "psa_key_policy_init()" call is deprecated by newer versions of PSA API, or outright removed, or something? (Can there be problem with someone wanting to use pkcs11-psa shim against different versions of PSA/TF-M?)

These questions are largely about the original, 1st commit here.

I see that the 2nd commit has more detailed description, which is really helpful. But:

> Replace TLS NamedCureve ID with Mbedtls ECP **groud** ID and  **covert** it to
PSA ECC family ID.

Are highlighted words typos? 

@CharleyChu, I hope you could shed some light on the questions above, and hopefully fix the typos before merging.

Finally, if this blocks/breaks something, and thus should be merged sooner rather than later, please leave the comments about that (preferrably with some details/links, so we can learn from it).

Thanks!

**Comment by CharleyChu** [comment]
@pfalcon @Sherryzhang2 Thanks for the review. I have updated the commit messages based your feedback.

**Review by pfalcon — APPROVED** [review]

**Comment by pfalcon** [comment]
@CharleyChu: Looks much better, thanks.

I also tried to run this PR thru CI workflow I'm working on, and it confirmed that it builds against the upstream amazon-freertos repo (that run is at https://github.com/pfalcon/freertos-pkcs11-psa/pull/2 is anybody interested, I hope to brush up my CI changes before the end of week and submit for review). So, approving from my side too.

Leaving until tomorrow if @davwan01, @Sherryzhang2 or @galak would have any further comments, and will merge it then otherwise.

**Comment by Sherryzhang2** [comment]
I am OK with this PR. No further comment from my side.

**Pull request merged**
