### PR TITLE
Update to TF-M version TF-Mv1.4.0

### PR DESCRIPTION
**Pull request by Sherryzhang2**
Signed-off-by: Sherry Zhang <sherry.zhang2@arm.com>
Change-Id: I0e71c9fe26079ad81705701be36044b7e09d32bf

### CODE REVIEW

**Comment by Sherryzhang2** [comment]
The CI failure is caused by the -TFM version in `vendors\cypress\MTB\psoc6\psoc64tfm\COMPONENT_TFM_NS_INTERFACE` is not aligned to TF-M V1.4.

**Comment by Sherryzhang2** [comment]
@galak  Can you help review this PR?

**Comment by davwan01** [comment]
Thanks for the update to the latest TF-M (v1.4.0) release.
A few questions:
* Could you check if this statement is still valid in README? Seems the update is related to Crypto

> It follows the PSA Cryptography API V1.0 beta3 and PSA Storage API V1.0.

* Seems the compatible version(s) of TF-M was not listed in the readme. Shall we list it somewhere to make the user clear that the shim layer works with which version(s)?
* Which platform have you tested/verified?
*

**Comment by davwan01** [comment]
> * The PSA Crypto API version is a mix of 1.0 beta 3 and 1.0. So maybe I can change it to 1.0?
Is it a good idea to mention the mix and also provide the mbedTLS version (my understanding is that the API version is from what it is in mbedTLS, might be wrong) 

> * The initial thought is that TF-M is not mentioned at all and this shim layer works with all the implementation as long as it follows the PSA Crypto API and PSA Storage API. So I mentioned the API version instead of the TF-M version.

OK, that makes sense then.
>* I have verified it on Arm Musca_b1 board.

**Comment by pfalcon** [comment]
@Sherryzhang2: Thanks for the patch.

> @galak Can you help review this PR?

@galak is on vacation this week, but I will try to do my best.

> The CI failure is caused by the -TFM version in vendors\cypress\MTB\psoc6\psoc64tfm\COMPONENT_TFM_NS_INTERFACE is not aligned to TF-M V1.4.

For my own reference, it's https://github.com/aws/amazon-freertos/blob/main/vendors/cypress/MTB/psoc6/psoc64tfm/COMPONENT_TFM_NS_INTERFACE/include/psa/crypto_sizes.h#L598 which contains an older macro PSA_KEY_EXPORT_MAX_SIZE(), which gets replaced with PSA_EXPORT_KEY_OUTPUT_SIZE() in this PR.

But we need to have a working CI for this project, so we either need to ping/help with the upgrade, or switch to another board as the build target.

> Is there any plan to update the TF-M version on the psoc64 platform?

That's a good question, ping @CharleyChu  (as the author of previous PSoC64 related patches).

> I have verified it on Arm Musca_b1 board.

Can you please provide the relevant command line(s), so I can update the CI?

**Comment by pfalcon** [comment]
> >        The PSA Crypto API version is a mix of 1.0 beta 3 and 1.0. So maybe I can change it to 1.0?

> Is it a good idea to mention the mix and also provide the mbedTLS version (my understanding is that the API version is from what it is in mbedTLS, might be wrong)

>        The initial thought is that TF-M is not mentioned at all and this shim layer works with all the implementation as long as it follows the PSA Crypto API and PSA Storage API. So I mentioned the API version instead of the TF-M version.

So, what about such things as PSA_KEY_EXPORT_MAX_SIZE -> PSA_EXPORT_KEY_OUTPUT_SIZE macro renamings? Are they covered by PSA version increments? If yes, then the README apparently should be updated. (And if somehow not, then I'd second the idea to specify which TF-M version(s) the project was tested with).

**Comment by Sherryzhang2** [comment]
> @Sherryzhang2:
> 
> > Do you mean the command line when building TF-M? I used the following build commands:
> 
> No, I mean the command line to build any FreeRTOS sample/demo, with the changed (and actually, unchanged too) freertos-pkcs11-psa submodule. As I mentioned above, we need to keep CI green before and after the change. Here's the script we currently use for CI build: https://github.com/Linaro/freertos-pkcs11-psa/blob/master/.github/workflows/build.sh . What needs to be changed in it to build for the Arm Musca_b1 board?

This build script does not need to be changed. The solution is to use TF-M V1.4 IN https://github.com/aws/amazon-freertos/tree/main/vendors/cypress/MTB/psoc6/psoc64tfm. Currently, TFM v1.2 is used.

**Comment by pfalcon** [comment]
> This build script does not need to be changed. The solution is to use TF-M V1.4 IN https://github.com/aws/amazon-freertos/tree/main/vendors/cypress/MTB/psoc6/psoc64tfm. Currently, TFM v1.2 is used.

Sounds good, is a PR for that already submitted upstream?

**Comment by pfalcon** [comment]
Ok. @galak should be back from vacation this week, so I'd defer to him further review (more specifically, deciding whether this can/should be merged ahead of upstream update).

**Comment by Sherryzhang2** [comment]
Any comment on this PR?

**Comment by Sherryzhang2** [comment]
> Ok. @galak should be back from vacation this week, so I'd defer to him further review (more specifically, deciding whether this can/should be merged ahead of upstream update).

@galak  @pfalcon Any update?

**Comment by pfalcon** [comment]
> @galak @pfalcon Any update?

I pinged @galak, so hopefully he'll look into this.

From my side, I don't have other comments beyond what was already said: technical-wise, it's not a good situation when a PR breaks CI, and that's why I don't give this +1. We either need to "fix" PR, or "fix" CI. Of, organizational-wise, that may be not always possible. So, if you'd rather have this merged now, and look into recovering CI some time later - well, I can understand that such exception may happen, so feel free to go ahead and merge it.

**Comment by Sherryzhang2** [comment]
> > > @galak @pfalcon Any update?
> > 
> > 
> > I pinged @galak, so hopefully he'll look into this.
> > From my side, I don't have other comments beyond what was already said: technical-wise, it's not a good situation when a PR breaks CI, and that's why I don't give this +1. We either need to "fix" PR, or "fix" CI. Of, organizational-wise, that may be not always possible. So, if you'd rather have this merged now, and look into recovering CI some time later - well, I can understand that such exception may happen, so feel free to go ahead and merge it.
> 
> I prefer fix the CI and then merge it. The CI help test the code. I do not want to break the normal work flow. @galak can you have a look at this PR?

@galak  Can you have a look at this PR? Thanks!

**Comment by Sherryzhang2** [comment]
Any comment on this PR? If CI always fails, I would suggest merging it without waiting for CI recovery.

**Comment by pfalcon** [comment]
@Sherryzhang2: @galak no longer works on these projects. Given that this patch stayed too long in queue, and no other solution was proposed/surfaced, I'm going to merge this as is.

**Pull request merged**
