### PR TITLE
Add the technical information in the ReadMe.md

### PR DESCRIPTION
**Pull request by Sherryzhang2**
-  Add the functionality description section in ReadMe.

-  Add the integration guide in ReadMe.

### CODE REVIEW

**Review by pfalcon — APPROVED** [review]
This looks good as a high-level description, thanks!

There may be not enough specific details, but I guess that's exactly what our task here at Linaro is - to provide more detailed integration instructions, likely encoded as "executable documentation" of CI scripts.

**Comment by pfalcon** [comment]
@galak: Can you please check if this is ok to merge?

**Comment by davwan01** [comment]
Hi,
Just let us know if any further comments.
Thanks.

**Review by galak — APPROVED** [review]

**Comment by pfalcon** [comment]
@Sherryzhang2, @davwan01: Thanks for your patience and sorry for delay as we settle on the maintenance process here.

I've merged it now. I used "Rebase and merge" to avoid a git merge commit in the repo, and thus have a clearer git history (a common practice nowadays). Let me know if anybody is concerned.

Thanks.

**Comment by davwan01** [comment]
Hi @pfalcon , thanks!
I like the clear history too! 😁

**Pull request merged**
